baseurl = "http://fintrospect.io"
title = "fintrospect"
theme = "hugo-universal-theme"
languageCode = "en-us"
googleAnalytics = ""

[params]
    author = "fintrospect"
    style = "blue"
    copyright = "Copyright (c) 2015 - 2016, YourCompany; all rights reserved."
    date_format = "2100-01-01"
    logo = "img/logo.png"

[[params.menu]]
    name = "home"
    url  = "/"

[[params.menu]]
    name = "cookbook"
    url  = "/cookbook"

[[params.menu]]
    name = "api"
    url  = "/api"

[[params.menu]]
    name = "twitter"
    url  = "https://twitter.com/fintrospectdev"

[[params.menu]]
    name = "github"
    url  = "https://github.com/daviddenton/fintrospect"

[params.testimonials]
    title = "Testimonials"
    subtitle = "We have worked with many clients and we always like to hear they come out from the cooperation happy and satisfied. Have a look what our clients said about us."

[params.see_more]
    icon = "fa fa-file-code-o"
    title = "Do you want to see more?"
    subtitle = "We have prepared for you more than 40 different HTML pages, including 5 variations of homepage."
    link_url = "#"
    link_text = "Check other homepages"

[params.clients]
    title = "Our Clients"
    subtitle = ""
