baseurl = "http://fintrospect.io"
title = "Fintrospect"
theme = "hugo-universal-theme"
languageCode = "en-us"
googleAnalytics = ""

paginate = 10

[params]
    viewMorePostLink = "/blog/"
    author = "fintrospect"

    style = "blue"

    email = "your@email.com"

    about_us = "<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>"
    copyright = "Copyright (c) 2015 - 2016, YourCompany; all rights reserved."
    date_format = "2006-01-02"
    logo = "img/logo.png"
    address = """<p><strong>Universal Ltd.</strong>
        <br>13/25 New Avenue
        <br>Newtown upon River
        <br>45Y 73J
        <br>England
        <br>
        <strong>Great Britain</strong>
      </p>
      """
    latitude = "-12.043333"
    longitude = "-77.028333"

[Permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

[[params.menu]]
    name = "home"
    url  = "/"

[[params.menu]]
    name = "cookbook"
    url  = "/cookbook"

[[params.menu]]
    name = "api"
    url  = "/api"

[[params.menu]]
    name = "faq"
    url  = "/faq"

[[params.menu]]
    name = "contact"
    url  = "/contact"

[[params.menu]]
    name = "twitter"
    url  = "https://twitter.com/fintrospectdev"

[[params.menu]]
    name = "github"
    url  = "https://github.com/daviddenton/fintrospect"

[params.widgets]
    categories = true
    tags = true
    search = true

[params.carousel]
    enable = true

[params.features]
    enable = true

[params.testimonials]
    enable = true
    title = "Testimonials"
    subtitle = "We have worked with many clients and we always like to hear they come out from the cooperation happy and satisfied. Have a look what our clients said about us."

[params.see_more]
    enable = true
    icon = "fa fa-file-code-o"
    title = "Do you want to see more?"
    subtitle = "We have prepared for you more than 40 different HTML pages, including 5 variations of homepage."
    link_url = "#"
    link_text = "Check other homepages"

[params.clients]
    enable = true
    title = "Our Clients"
    subtitle = ""

[params.recent_posts]
    enable = true
    title = "From our blog"
    subtitle = "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo."

