package io.fintrospect.parameters

import java.time.format.DateTimeFormatter.{ISO_LOCAL_DATE, ISO_LOCAL_DATE_TIME, ISO_ZONED_DATE_TIME}
import java.time.{LocalDate, LocalDateTime, ZonedDateTime}
import java.util.UUID

import io.fintrospect.formats.json.{Argo, JsonFormat}

import scala.xml.{Elem, XML}

/**
  * Spec required to marshall and demarshall a parameter of a custom type
  * @param deserialize function to take the input string from the request and attempt to construct a deserialized instance of T. Exceptions are
  *                    automatically caught and translated into the appropriate result, so just concentrate on the Happy-path case
  * @param paramType The parameter type to be used in the documentation. For custom types, this is usually ObjectParamType (for JSON) or StringParamType
  * @param serialize function to take the input type and serialize it to a string to be represented in the request
  * @param description optional description of the parameter (for use in description endpoints)
  * @tparam T the type of the parameter
  * @return a parameter for retrieving a value of type [T] from the request
  */
case class ParameterSpec[T](name: String,
                            description: Option[String] = None,
                            paramType: ParamType,
                            deserialize: String => T,
                            serialize: T => String = (s: T) => s.toString)


/**
  * Convenience trait for which ParameterSpecs can be autogenerated. Required mixing in to AnyVals wrapper classes
  * to take advantage of this ability
  */
trait ParameterSpecVal[T] {
  val value: T
}

/**
  * Predefined ParameterSpec instances for common types
  */
object ParameterSpec {
  def localDate(name: String, description: String = null) = ParameterSpec[LocalDate](name, Option(description), StringParamType, LocalDate.parse(_), ISO_LOCAL_DATE.format(_))

  def zonedDateTime(name: String, description: String = null) = ParameterSpec[ZonedDateTime](name, Option(description), StringParamType, ZonedDateTime.parse(_), ISO_ZONED_DATE_TIME.format(_))

  def dateTime(name: String, description: String = null) = ParameterSpec[LocalDateTime](name, Option(description), StringParamType, LocalDateTime.parse(_), ISO_LOCAL_DATE_TIME.format(_))

  def boolean(name: String, description: String = null) = ParameterSpec[Boolean](name, Option(description), BooleanParamType, _.toBoolean, _.toString)

  def string(name: String, description: String = null) = ParameterSpec[String](name, Option(description), StringParamType, _.toString, _.toString)

  def uuid(name: String, description: String = null) = ParameterSpec[UUID](name, Option(description), StringParamType, UUID.fromString, _.toString)

  def bigDecimal(name: String, description: String = null) = ParameterSpec[BigDecimal](name, Option(description), NumberParamType, BigDecimal(_), _.toString())

  def long(name: String, description: String = null) = ParameterSpec[Long](name, Option(description), IntegerParamType, _.toLong, _.toString)

  def int(name: String, description: String = null) = ParameterSpec[Int](name, Option(description), IntegerParamType, _.toInt, _.toString)

  def integer(name: String, description: String = null) = ParameterSpec[Integer](name, Option(description), IntegerParamType, new Integer(_), _.toString)

  def json[T](name: String, description: String = null, format: JsonFormat[T, _] = Argo.JsonFormat) = ParameterSpec[T](name, Option(description), ObjectParamType, format.parse, format.compact)

  def xml(name: String, description: String = null) = ParameterSpec[Elem](name, Option(description), StringParamType, XML.loadString, _.toString())

  object specVal {
    def bigDecimal[L <: ParameterSpecVal[BigDecimal]](fn: BigDecimal => L, name: String, description: String = null): ParameterSpec[L] =
      ParameterSpec[L](name, Option(description), StringParamType, s => fn(BigDecimal(s)), _.value.toString())

    def boolean[L <: ParameterSpecVal[Boolean]](fn: Boolean => L, name: String, description: String = null): ParameterSpec[L] =
      ParameterSpec[L](name, Option(description), BooleanParamType, s => fn(s.toBoolean), _.value.toString())

    def int[L <: ParameterSpecVal[Int]](fn: Int => L, name: String, description: String = null): ParameterSpec[L] =
      ParameterSpec[L](name, Option(description), IntegerParamType, s => fn(s.toInt), _.value.toString())

    def integer[L <: ParameterSpecVal[Integer]](fn: Integer => L, name: String, description: String = null): ParameterSpec[L] =
      ParameterSpec[L](name, Option(description), IntegerParamType, s => fn(s.toInt), _.value.toString())

    def long[L <: ParameterSpecVal[Long]](fn: Long => L, name: String, description: String = null): ParameterSpec[L] =
      ParameterSpec[L](name, Option(description), IntegerParamType, s => fn(s.toLong), _.value.toString())

    def localDate[L <: ParameterSpecVal[LocalDate]](fn: LocalDate => L, name: String, description: String = null): ParameterSpec[L] =
      ParameterSpec[L](name, Option(description), StringParamType, s => fn(LocalDate.parse(s)), s => ISO_LOCAL_DATE.format(s.value))

    def dateTime[L <: ParameterSpecVal[LocalDateTime]](fn: LocalDateTime => L, name: String, description: String = null): ParameterSpec[L] =
      ParameterSpec[L](name, Option(description), StringParamType, s => fn(LocalDateTime.parse(s)), s => ISO_LOCAL_DATE_TIME.format(s.value))

    def zonedDateTime[L <: ParameterSpecVal[ZonedDateTime]](fn: ZonedDateTime => L, name: String, description: String = null): ParameterSpec[L] =
      ParameterSpec[L](name, Option(description), StringParamType, s => fn(ZonedDateTime.parse(s)), s => ISO_ZONED_DATE_TIME.format(s.value))

    def uuid[L <: ParameterSpecVal[UUID]](fn: UUID => L, name: String, description: String = null): ParameterSpec[L] =
      ParameterSpec[L](name, Option(description), StringParamType, s => fn(UUID.fromString(s)), _.value.toString)

    def string[L <: ParameterSpecVal[String]](fn: String => L, name: String, description: String = null): ParameterSpec[L] =
      ParameterSpec[L](name, Option(description), StringParamType, fn, _.value.toString)
  }

}
