package io.fintrospect.formats.json

import io.fintrospect.util.json.Json4s

class JsonNativeBuilderTest extends JsonResponseBuilderSpec(Json4s.Native)
class Json4NativeDoubleBuilderTest extends JsonResponseBuilderSpec(Json4s.NativeDoubleMode)

class Json4JacksonBuilderTest extends JsonResponseBuilderSpec(Json4s.Jackson)
class Json4JacksonDoubleBuilderTest extends JsonResponseBuilderSpec(Json4s.JacksonDoubleMode)